import type { Metadata } from "next";
import { Chewy, Lexend_Deca } from "next/font/google"; // Import Chewy and Lexend Deca fonts
import Link from "next/link"; // Import Link
import "./globals.css";

// Instantiate Chewy font
const chewy = Chewy({
  variable: "--font-chewy", // Define CSS variable for Chewy
  subsets: ["latin"],
  weight: "400", // Chewy only supports 400 weight
});
// Instantiate Lexend Deca font
const lexendDeca = Lexend_Deca({
  variable: "--font-lexend-deca", // Define CSS variable for Lexend Deca
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Specify available weights
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${chewy.variable} ${lexendDeca.variable} antialiased`}> {/* Apply Chewy and Lexend Deca font variables */}
        <nav className="bg-gray-100 p-4 border-b">
          <div className="container mx-auto flex space-x-4">
            <Link href="/" className="text-blue-600 hover:underline">Home</Link>
            <Link href="/storylines" className="text-blue-600 hover:underline">Storylines</Link>
          </div>
        </nav>
        <main>{children}</main> {/* Wrap children in main for semantics */}
      </body>
    </html>
  );
}
