import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link"; // Import Link
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-100 p-4 border-b">
          <div className="container mx-auto flex space-x-4">
            <Link href="/" className="text-blue-600 hover:underline">Home</Link>
            <Link href="/documents" className="text-blue-600 hover:underline">Documents</Link>
          </div>
        </nav>
        <main>{children}</main> {/* Wrap children in main for semantics */}
      </body>
    </html>
  );
}
