import type { Metadata } from "next";
import { Outfit, Lexend_Deca } from "next/font/google"; // Import Outfit and Lexend Deca fonts
import Link from "next/link"; // Import Link
import Providers from "./Providers";
import SDApplicationBar from "@/components/SDApplicationBar";
import AppHeader from "@/components/AppHeader";
import "./globals.css";
import { BookOpen, PlusCircle } from 'lucide-react';

// Instantiate Outfit font
const outfit = Outfit({
  variable: "--font-outfit", // Define CSS variable for Outfit
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Outfit supports multiple weights
});
// Instantiate Lexend Deca font
const lexendDeca = Lexend_Deca({
  variable: "--font-lexend-deca", // Define CSS variable for Lexend Deca
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Specify available weights
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${lexendDeca.variable} antialiased`}> {/* Apply Outfit and Lexend Deca font variables */}
        <Providers>
          <main>{children}</main> {/* Wrap children in main for semantics */}
        </Providers>
      </body>
    </html>
  );
}
