"""Add foreign keys to StorylineProgress

Revision ID: 1dc79f0c8c5d
Revises: 83dd76e1c412
Create Date: 2025-04-11 12:54:12.371897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc79f0c8c5d'
down_revision: Union[str, None] = '83dd76e1c412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storyline_progress', sa.Column('storyline_id', sa.Integer(), nullable=False))
    op.add_column('storyline_progress', sa.Column('storyline_step_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'storyline_progress', 'storyline_step', ['storyline_step_id'], ['storyline_step_id'])
    op.create_foreign_key(None, 'storyline_progress', 'storyline', ['storyline_id'], ['storyline_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'storyline_progress', type_='foreignkey')
    op.drop_constraint(None, 'storyline_progress', type_='foreignkey')
    op.drop_column('storyline_progress', 'storyline_step_id')
    op.drop_column('storyline_progress', 'storyline_id')
    # ### end Alembic commands ###
