"""Add student table

Revision ID: d014ff85f4db
Revises: 1dc79f0c8c5d
Create Date: 2025-04-16 09:12:32.198486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd014ff85f4db'
down_revision: Union[str, None] = '1dc79f0c8c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('style', sa.String(), nullable=False),
    sa.Column('interests', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('friends', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('document_pathname_key', table_name='document')
    op.drop_index('document_url_key', table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pathname', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('contentType', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contentDisposition', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='document_pkey')
    )
    op.create_index('document_url_key', 'document', ['url'], unique=True)
    op.create_index('document_pathname_key', 'document', ['pathname'], unique=True)
    op.drop_table('student')
    # ### end Alembic commands ###
